[package]
name = "preimage"
type = "bin"
authors = [""]

[dependencies]
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
poseidon2 = { tag = "v0.4.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2"}