password="0x0101010101010101010101010101010101010101010101010101010101010101"
expected_hash=[149,21,4,144,113,237,145,49,73,168,13,59,183,137,31,205,76,108,30,61,20,173,135,137,57,168,15,155,154,145,224,140]
user_address="0x0202020202020202020202020202020202020202020202020202020202020202"
vault_id="0x0303030303030303030303030303030303030303030303030303030303030303"
nullifier=[54,86,189,130,53,109,55,19,121,156,192,44,81,78,170,133,14,227,109,168,216,171,104,212,100,2,36,39,210,97,145,38]